### ISSUE TITLE
Problem in my Sum Program

### ISSUE THREAD

**Issue by MCILearner** [MCILearner/Cpp-Programming#2]
After making the last commit  [be1f5eb](https://github.com/MCILearner/Cpp-Programming/commit/be1f5ebc54f2cb2d9d70e15db610b80035af929b)  in my sum program the program is not working properly.

**Comment by MCILearner** [comment]
Thanks

**Comment by MCILearner** [comment]
Testing

**Comment by HammadMaqbool** [comment]
after checking it
